### PR TITLE
Delete .prettierrc

### PR DESCRIPTION
**Pull request by dakotareier**
Prettier is a product developed by Facebook.

### CODE REVIEW

**Comment by andybelldesign** [comment]
Im not sure it is: https://github.com/prettier

Have you got any evidence?

**Comment by Halooo** [comment]
https://github.com/prettier/prettier/graphs/contributors

**Comment by andybelldesign** [comment]
Fair enough. I think as the nature of this project is to provide alternatives, we should do exactly that, personally.

Anyone know of a good alternative?

**Comment by vjeux** [comment]
@andybelldesign Sorry, I'm the top contributor for prettier and worked on it with the sole purpose of solving our pretty printing problems at Facebook. You'll have to find an alternative for this as well :(

**Comment by Daniel15** [comment]
You'd probably want to remove Babel and Babylon too 😄

**Pull request closed without merging**
